export function buildProjectEnvTemplate(example: boolean): string {
  const providerKey = example ? "replace-with-your-provider-key" : "";

  return [
    "# Kitty CLI environment template",
    example
      ? "# Copy this file to .kitty/.env and fill real credentials."
      : "# This file stores local runtime credentials for the current project.",
    example
      ? "# .kitty/.env.example may be committed; never commit .kitty/.env."
      : "# Keep secrets in this file only; do not commit it.",
    "# Non-model runtime settings are listed first; provider and model settings are at the bottom.",
    "",
    "# Telegram private chat settings",
    `KITTY_TELEGRAM_TOKEN=${example ? "replace-with-your-telegram-bot-token" : ""}`,
    `KITTY_TELEGRAM_ALLOWED_USER_IDS=${example ? "replace-with-your-telegram-user-id" : ""}`,
    "KITTY_TELEGRAM_API_BASE_URL=https://api.telegram.org",
    "KITTY_TELEGRAM_PROXY_URL=",
    "KITTY_TELEGRAM_POLLING_TIMEOUT_SECONDS=50",
    "KITTY_TELEGRAM_POLLING_LIMIT=100",
    "KITTY_TELEGRAM_POLLING_RETRY_BACKOFF_MS=1000",
    "KITTY_TELEGRAM_MESSAGE_CHUNK_CHARS=3500",
    "KITTY_TELEGRAM_TYPING_INTERVAL_MS=4000",
    "KITTY_TELEGRAM_DELIVERY_MAX_RETRIES=6",
    "KITTY_TELEGRAM_DELIVERY_BASE_DELAY_MS=1000",
    "KITTY_TELEGRAM_DELIVERY_MAX_DELAY_MS=30000",
    "",
    "# Context and output settings",
    "# These mirror current runtime defaults; code still clamps invalid extremes.",
    "KITTY_CONTEXT_WINDOW_MESSAGES=120",
    "KITTY_MAX_CONTEXT_CHARS=900000",
    "KITTY_CONTEXT_SUMMARY_CHARS=120000",
    "KITTY_MAX_OUTPUT_TOKENS=384000",
    "",
    "# Tool IO budgets",
    "KITTY_MAX_READ_BYTES=120000",
    "KITTY_PROJECT_DOC_MAX_BYTES=24576",
    "KITTY_COMMAND_STALL_TIMEOUT_MS=30000",
    "KITTY_SHOW_REASONING=true",
    "",
    "# Agent profile settings",
    "# Built-in agent profile: intp",
    "KITTY_PROFILE=intp",
    "",
    "# Provider / model settings",
    "# Runtime reads one active provider block. Keep exactly one provider block uncommented.",
    "",
    "# Provider preset: YLS Codex + GPT-5.4",
    "# KITTY_PROVIDER=openai",
    `# KITTY_API_KEY=${providerKey || "replace-with-your-provider-key"}`,
    "# KITTY_BASE_URL=https://code.ylsagi.com/codex",
    "# KITTY_MODEL=gpt-5.4",
    "# KITTY_THINKING=disabled",
    "# KITTY_REASONING_EFFORT=xhigh",
    "# GPT reasoning effort: minimal | low | medium | high | xhigh",
    "",
    "# Provider preset: TTAPI + GPT-5.4",
    "# KITTY_PROVIDER=openai",
    `# KITTY_API_KEY=${providerKey || "replace-with-your-provider-key"}`,
    "# KITTY_BASE_URL=https://w.ciykj.cn",
    "# KITTY_MODEL=gpt-5.4",
    "# KITTY_THINKING=disabled",
    "# KITTY_REASONING_EFFORT=xhigh",
    "# GPT reasoning effort: minimal | low | medium | high | xhigh",
    "",
    "# Provider preset: DeepSeek official V4",
    "KITTY_PROVIDER=deepseek",
    `KITTY_API_KEY=${providerKey}`,
    "KITTY_BASE_URL=https://api.deepseek.com",
    "KITTY_MODEL=deepseek-v4-flash",
    "KITTY_THINKING=enabled",
    "KITTY_REASONING_EFFORT=max",
    "# DeepSeek V4 model: deepseek-v4-flash | deepseek-v4-pro",
    "# DeepSeek V4 thinking: enabled | disabled",
    "# DeepSeek V4 reasoning effort: high | max",
    "",
  ].join("\n");
}
