export function buildProjectEnvTemplate(example: boolean): string {
  const deadmouseApiKeyLine = "DEADMOUSE_API_KEY=replace-with-your-key";

  return [
    "# Deadmouse CLI environment template",
    example
      ? "# Copy this file to .deadmouse/.env and fill real credentials."
      : "# This file stores local runtime credentials for the current project.",
    example
      ? "# .deadmouse/.env.example may be committed; never commit .deadmouse/.env."
      : "# Keep secrets in this file only; do not commit it.",
    "# Non-model runtime settings are listed first; provider and model settings are at the bottom.",
    "",
    "# Playwright MCP default settings",
    "DEADMOUSE_MCP_ENABLED=true",
    "DEADMOUSE_MCP_PLAYWRIGHT_ENABLED=true",
    "DEADMOUSE_MCP_PLAYWRIGHT_BROWSER=chromium",
    "DEADMOUSE_MCP_PLAYWRIGHT_HEADLESS=true",
    "DEADMOUSE_MCP_PLAYWRIGHT_OUTPUT_MODE=file",
    "DEADMOUSE_MCP_PLAYWRIGHT_SAVE_SESSION=true",
    "",
    "# Telegram private chat settings",
    "DEADMOUSE_TELEGRAM_TOKEN=replace-with-your-token",
    "DEADMOUSE_TELEGRAM_ALLOWED_USER_IDS=replace-with-your-telegram-user-id",
    "# DEADMOUSE_TELEGRAM_API_BASE_URL=https://api.telegram.org",
    "# DEADMOUSE_TELEGRAM_PROXY_URL=http://127.0.0.1:7897",
    "# DEADMOUSE_TELEGRAM_POLLING_TIMEOUT_SECONDS=50",
    "# DEADMOUSE_TELEGRAM_POLLING_LIMIT=100",
    "# DEADMOUSE_TELEGRAM_POLLING_RETRY_BACKOFF_MS=1000",
    "# DEADMOUSE_TELEGRAM_MESSAGE_CHUNK_CHARS=3500",
    "# DEADMOUSE_TELEGRAM_TYPING_INTERVAL_MS=4000",
    "# DEADMOUSE_TELEGRAM_DELIVERY_MAX_RETRIES=6",
    "# DEADMOUSE_TELEGRAM_DELIVERY_BASE_DELAY_MS=1000",
    "# DEADMOUSE_TELEGRAM_DELIVERY_MAX_DELAY_MS=30000",
    "",
    "# MinerU standard API settings",
    "MINERU_API_TOKEN=replace-with-your-token",
    "MINERU_BASE_URL=https://mineru.net/api/v4",
    "MINERU_MODEL_VERSION=vlm",
    "MINERU_LANGUAGE=ch",
    "MINERU_ENABLE_TABLE=true",
    "MINERU_ENABLE_FORMULA=true",
    "MINERU_POLL_INTERVAL_MS=2000",
    "MINERU_TIMEOUT_MS=300000",
    "",
    "# Provider / model settings",
    "# Profile 1: GPT-5.4",
    "DEADMOUSE_PROVIDER=openai",
    deadmouseApiKeyLine,
    "DEADMOUSE_BASE_URL=https://w.ciykj.cn",
    "DEADMOUSE_MODEL=gpt-5.4",
    "DEADMOUSE_PROFILE=intp",
    "DEADMOUSE_REASONING_EFFORT=xhigh",
    "# GPT reasoning effort: minimal | low | medium | high | xhigh",
    "",
    "# Profile 2: DeepSeek official V4",
    "# DEADMOUSE_PROVIDER=deepseek",
    "# DEADMOUSE_API_KEY=replace-with-your-key",
    "# DEADMOUSE_BASE_URL=https://api.deepseek.com",
    "# DEADMOUSE_MODEL=deepseek-v4-flash",
    "# DEADMOUSE_PROFILE=intp",
    "# DEADMOUSE_THINKING=enabled",
    "# DEADMOUSE_REASONING_EFFORT=high",
    "# DeepSeek V4 model: deepseek-v4-flash | deepseek-v4-pro",
    "# DeepSeek V4 thinking: enabled | disabled",
    "# DeepSeek V4 reasoning effort: high | max",
    "",
    "# Profile 3: SiliconFlow + DeepSeek V3.2",
    "# DEADMOUSE_PROVIDER=openai-compatible",
    "# DEADMOUSE_API_KEY=replace-with-your-key",
    "# DEADMOUSE_BASE_URL=https://api.siliconflow.cn/v1",
    "# DEADMOUSE_MODEL=deepseek-ai/DeepSeek-V3.2",
    "# DEADMOUSE_PROFILE=intp",
    "",
  ].join("\n");
}
