import type { ExecutionRecord } from "../../execution/types.js";

export function executionRecordValues(record: ExecutionRecord): unknown[] {
  return [
    record.id,
    record.lane,
    record.profile,
    record.launch,
    record.requestedBy,
    record.actorName,
    record.actorRole ?? null,
    record.taskId ?? null,
    record.objectiveKey ?? null,
    record.objectiveText ?? null,
    record.cwd,
    record.status,
    record.worktreePolicy,
    record.worktreeName ?? null,
    record.sessionId ?? null,
    record.pid ?? null,
    record.prompt ?? null,
    record.command ?? null,
    record.timeoutMs ?? null,
    record.stallTimeoutMs ?? null,
    record.waitPolicy ? JSON.stringify(record.waitPolicy) : null,
    record.assignmentId ?? null,
    record.assignmentSnapshot ? JSON.stringify(record.assignmentSnapshot) : null,
    record.capabilityId ?? null,
    record.capabilityKind ?? null,
    record.capabilityPackageSnapshot ? JSON.stringify(record.capabilityPackageSnapshot) : null,
    record.executionPolicy ? JSON.stringify(record.executionPolicy) : null,
    record.summary ?? null,
    record.resultText ?? null,
    record.output ?? null,
    record.exitCode ?? null,
    record.pauseReason ?? null,
    record.statusDetail ?? null,
    record.createdAt,
    record.updatedAt,
    record.finishedAt ?? null,
  ];
}
